$kind: http-request
name: "product: createNewProduct"
url: localhost:3003/admin/product/create
method: POST
body:
  type: formdata
  content:
    - type: file
      key: productImages
      src:
        - /C:/Users/Mysterio95/Downloads/Telegram Desktop/2.jpg
      description: ""
      disabled: false
order: 4489691186697606
